var express = require('express');
var router = express.Router();

var Event = require('../models/events.js');

var newEvents = [{
  "description": "nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at",
  "link": "http://deliciousdays.com/neque/libero/convallis/eget/eleifend/luctus.jsp?aliquet=integer&pulvinar=aliquet&sed=massa&nisl=id&nunc=lobortis&rhoncus=convallis&dui=tortor&vel=risus&sem=dapibus&sed=augue&sagittis=vel&nam=accumsan&congue=tellus&risus=nisi&semper=eu&porta=orci&volutpat=mauris&quam=lacinia&pede=sapien&lobortis=quis&ligula=libero&sit=nullam&amet=sit&eleifend=amet&pede=turpis&libero=elementum&quis=ligula&orci=vehicula&nullam=consequat&molestie=morbi&nibh=a&in=ipsum&lectus=integer&pellentesque=a&at=nibh&nulla=in&suspendisse=quis&potenti=justo&cras=maecenas&in=rhoncus&purus=aliquam&eu=lacus&magna=morbi&vulputate=quis&luctus=tortor&cum=id&sociis=nulla&natoque=ultrices&penatibus=aliquet&et=maecenas&magnis=leo&dis=odio&parturient=condimentum&montes=id&nascetur=luctus&ridiculus=nec&mus=molestie&vivamus=sed&vestibulum=justo&sagittis=pellentesque&sapien=viverra&cum=pede&sociis=ac&natoque=diam&penatibus=cras&et=pellentesque&magnis=volutpat&dis=dui&parturient=maecenas&montes=tristique&nascetur=est&ridiculus=et&mus=tempus&etiam=semper&vel=est&augue=quam&vestibulum=pharetra&rutrum=magna&rutrum=ac&neque=consequat&aenean=metus&auctor=sapien&gravida=ut",
  "photo": "http://dummyimage.com/600x600.png/dddddd/000000"
}, {
  "description": "pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at",
  "link": "https://about.me/ante/vel/ipsum/praesent/blandit/lacinia.json?in=amet&faucibus=turpis&orci=elementum&luctus=ligula&et=vehicula&ultrices=consequat&posuere=morbi&cubilia=a&curae=ipsum&duis=integer&faucibus=a&accumsan=nibh&odio=in&curabitur=quis&convallis=justo&duis=maecenas&consequat=rhoncus&dui=aliquam&nec=lacus&nisi=morbi&volutpat=quis&eleifend=tortor&donec=id&ut=nulla&dolor=ultrices&morbi=aliquet&vel=maecenas&lectus=leo&in=odio&quam=condimentum&fringilla=id&rhoncus=luctus&mauris=nec&enim=molestie&leo=sed&rhoncus=justo&sed=pellentesque&vestibulum=viverra&sit=pede&amet=ac&cursus=diam&id=cras&turpis=pellentesque&integer=volutpat&aliquet=dui&massa=maecenas&id=tristique&lobortis=est&convallis=et&tortor=tempus&risus=semper&dapibus=est&augue=quam&vel=pharetra&accumsan=magna&tellus=ac&nisi=consequat&eu=metus",
  "photo": "http://dummyimage.com/600x600.png/cc0000/ffffff"
}, {
  "description": "eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend",
  "link": "https://nyu.edu/sed/vestibulum/sit.jpg?ut=purus&massa=phasellus&quis=in&augue=felis&luctus=donec&tincidunt=semper&nulla=sapien&mollis=a&molestie=libero&lorem=nam&quisque=dui&ut=proin&erat=leo&curabitur=odio&gravida=porttitor&nisi=id&at=consequat&nibh=in&in=consequat&hac=ut&habitasse=nulla&platea=sed&dictumst=accumsan&aliquam=felis&augue=ut&quam=at&sollicitudin=dolor&vitae=quis&consectetuer=odio&eget=consequat&rutrum=varius&at=integer&lorem=ac&integer=leo&tincidunt=pellentesque&ante=ultrices&vel=mattis&ipsum=odio&praesent=donec&blandit=vitae&lacinia=nisi&erat=nam&vestibulum=ultrices&sed=libero&magna=non&at=mattis&nunc=pulvinar&commodo=nulla&placerat=pede&praesent=ullamcorper&blandit=augue&nam=a&nulla=suscipit&integer=nulla&pede=elit&justo=ac&lacinia=nulla&eget=sed&tincidunt=vel&eget=enim&tempus=sit&vel=amet&pede=nunc&morbi=viverra&porttitor=dapibus&lorem=nulla&id=suscipit&ligula=ligula&suspendisse=in&ornare=lacus&consequat=curabitur&lectus=at&in=ipsum&est=ac&risus=tellus&auctor=semper&sed=interdum&tristique=mauris&in=ullamcorper&tempus=purus&sit=sit&amet=amet&sem=nulla&fusce=quisque&consequat=arcu&nulla=libero&nisl=rutrum",
  "photo": "http://dummyimage.com/600x600.png/5fa2dd/ffffff"
}, {
  "description": "faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci",
  "link": "https://disqus.com/quisque/arcu/libero.png?aliquam=turpis&augue=enim&quam=blandit&sollicitudin=mi&vitae=in&consectetuer=porttitor&eget=pede&rutrum=justo&at=eu&lorem=massa&integer=donec&tincidunt=dapibus&ante=duis&vel=at&ipsum=velit&praesent=eu",
  "photo": "http://dummyimage.com/600x600.png/ff4444/ffffff"
}, {
  "description": "pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam",
  "link": "https://sfgate.com/sed/sagittis/nam/congue/risus.jsp?nisl=pulvinar",
  "photo": "http://dummyimage.com/600x600.png/cc0000/ffffff"
}, {
  "description": "amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus",
  "link": "http://yale.edu/curae.aspx?mauris=lobortis&sit=convallis&amet=tortor&eros=risus&suspendisse=dapibus&accumsan=augue&tortor=vel&quis=accumsan&turpis=tellus&sed=nisi&ante=eu&vivamus=orci&tortor=mauris&duis=lacinia&mattis=sapien&egestas=quis&metus=libero&aenean=nullam&fermentum=sit&donec=amet&ut=turpis&mauris=elementum&eget=ligula",
  "photo": "http://dummyimage.com/600x600.png/dddddd/000000"
}, {
  "description": "morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean",
  "link": "http://springer.com/semper/sapien.html?non=eu&interdum=mi&in=nulla&ante=ac&vestibulum=enim&ante=in&ipsum=tempor&primis=turpis&in=nec&faucibus=euismod&orci=scelerisque&luctus=quam&et=turpis&ultrices=adipiscing&posuere=lorem&cubilia=vitae&curae=mattis&duis=nibh&faucibus=ligula&accumsan=nec&odio=sem&curabitur=duis&convallis=aliquam&duis=convallis&consequat=nunc&dui=proin&nec=at&nisi=turpis&volutpat=a&eleifend=pede&donec=posuere&ut=nonummy&dolor=integer&morbi=non&vel=velit&lectus=donec&in=diam&quam=neque&fringilla=vestibulum&rhoncus=eget&mauris=vulputate&enim=ut&leo=ultrices&rhoncus=vel&sed=augue&vestibulum=vestibulum&sit=ante&amet=ipsum&cursus=primis&id=in&turpis=faucibus&integer=orci&aliquet=luctus",
  "photo": "http://dummyimage.com/600x600.png/5fa2dd/ffffff"
}, {
  "description": "cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat",
  "link": "https://biblegateway.com/lacus.aspx?metus=dolor&aenean=sit&fermentum=amet&donec=consectetuer&ut=adipiscing&mauris=elit&eget=proin&massa=interdum&tempor=mauris&convallis=non&nulla=ligula&neque=pellentesque&libero=ultrices&convallis=phasellus&eget=id&eleifend=sapien&luctus=in&ultricies=sapien&eu=iaculis&nibh=congue&quisque=vivamus&id=metus&justo=arcu&sit=adipiscing&amet=molestie&sapien=hendrerit&dignissim=at&vestibulum=vulputate&vestibulum=vitae&ante=nisl&ipsum=aenean&primis=lectus&in=pellentesque&faucibus=eget&orci=nunc&luctus=donec&et=quis&ultrices=orci&posuere=eget&cubilia=orci&curae=vehicula&nulla=condimentum&dapibus=curabitur&dolor=in&vel=libero&est=ut&donec=massa&odio=volutpat&justo=convallis&sollicitudin=morbi&ut=odio&suscipit=odio&a=elementum&feugiat=eu&et=interdum&eros=eu&vestibulum=tincidunt&ac=in&est=leo&lacinia=maecenas&nisi=pulvinar&venenatis=lobortis&tristique=est&fusce=phasellus&congue=sit&diam=amet&id=erat&ornare=nulla&imperdiet=tempus&sapien=vivamus&urna=in&pretium=felis&nisl=eu&ut=sapien&volutpat=cursus&sapien=vestibulum&arcu=proin&sed=eu&augue=mi&aliquam=nulla",
  "photo": "http://dummyimage.com/600x600.png/5fa2dd/ffffff"
}, {
  "description": "nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac",
  "link": "https://wordpress.com/in/quam/fringilla/rhoncus/mauris.xml?quam=morbi&a=vel&odio=lectus&in=in&hac=quam&habitasse=fringilla&platea=rhoncus&dictumst=mauris&maecenas=enim&ut=leo&massa=rhoncus&quis=sed&augue=vestibulum&luctus=sit&tincidunt=amet&nulla=cursus&mollis=id&molestie=turpis&lorem=integer&quisque=aliquet&ut=massa&erat=id&curabitur=lobortis&gravida=convallis&nisi=tortor&at=risus&nibh=dapibus&in=augue&hac=vel&habitasse=accumsan&platea=tellus&dictumst=nisi&aliquam=eu&augue=orci&quam=mauris&sollicitudin=lacinia&vitae=sapien&consectetuer=quis&eget=libero&rutrum=nullam&at=sit&lorem=amet&integer=turpis&tincidunt=elementum&ante=ligula&vel=vehicula&ipsum=consequat&praesent=morbi&blandit=a&lacinia=ipsum&erat=integer",
  "photo": "http://dummyimage.com/600x600.png/ff4444/ffffff"
}, {
  "description": "massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar",
  "link": "https://oakley.com/elementum/pellentesque/quisque/porta.js?amet=imperdiet&diam=sapien&in=urna&magna=pretium&bibendum=nisl&imperdiet=ut&nullam=volutpat&orci=sapien&pede=arcu&venenatis=sed&non=augue&sodales=aliquam&sed=erat&tincidunt=volutpat&eu=in&felis=congue&fusce=etiam&posuere=justo&felis=etiam&sed=pretium&lacus=iaculis&morbi=justo&sem=in&mauris=hac&laoreet=habitasse&ut=platea&rhoncus=dictumst&aliquet=etiam&pulvinar=faucibus&sed=cursus&nisl=urna&nunc=ut&rhoncus=tellus&dui=nulla&vel=ut&sem=erat&sed=id&sagittis=mauris&nam=vulputate&congue=elementum&risus=nullam&semper=varius&porta=nulla&volutpat=facilisi",
  "photo": "http://dummyimage.com/600x600.png/dddddd/000000"
}, {
  "description": "vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla",
  "link": "https://oakley.com/aenean.html?nunc=in&donec=quis&quis=justo&orci=maecenas&eget=rhoncus&orci=aliquam&vehicula=lacus&condimentum=morbi&curabitur=quis&in=tortor&libero=id&ut=nulla&massa=ultrices&volutpat=aliquet&convallis=maecenas&morbi=leo&odio=odio&odio=condimentum&elementum=id&eu=luctus&interdum=nec&eu=molestie&tincidunt=sed&in=justo&leo=pellentesque&maecenas=viverra&pulvinar=pede&lobortis=ac&est=diam&phasellus=cras&sit=pellentesque&amet=volutpat&erat=dui&nulla=maecenas&tempus=tristique&vivamus=est&in=et&felis=tempus&eu=semper&sapien=est&cursus=quam&vestibulum=pharetra&proin=magna&eu=ac&mi=consequat&nulla=metus",
  "photo": "http://dummyimage.com/600x600.png/dddddd/000000"
}, {
  "description": "id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas",
  "link": "https://deliciousdays.com/lacus/morbi.jpg?arcu=montes&sed=nascetur&augue=ridiculus&aliquam=mus&erat=etiam&volutpat=vel&in=augue&congue=vestibulum&etiam=rutrum&justo=rutrum&etiam=neque&pretium=aenean&iaculis=auctor&justo=gravida&in=sem&hac=praesent&habitasse=id&platea=massa&dictumst=id&etiam=nisl&faucibus=venenatis&cursus=lacinia&urna=aenean&ut=sit&tellus=amet&nulla=justo&ut=morbi&erat=ut&id=odio&mauris=cras&vulputate=mi&elementum=pede&nullam=malesuada&varius=in&nulla=imperdiet&facilisi=et&cras=commodo&non=vulputate&velit=justo&nec=in&nisi=blandit&vulputate=ultrices&nonummy=enim&maecenas=lorem&tincidunt=ipsum&lacus=dolor&at=sit&velit=amet&vivamus=consectetuer&vel=adipiscing&nulla=elit&eget=proin&eros=interdum&elementum=mauris&pellentesque=non&quisque=ligula&porta=pellentesque&volutpat=ultrices&erat=phasellus&quisque=id&erat=sapien&eros=in&viverra=sapien&eget=iaculis&congue=congue&eget=vivamus&semper=metus&rutrum=arcu&nulla=adipiscing&nunc=molestie&purus=hendrerit&phasellus=at&in=vulputate&felis=vitae&donec=nisl&semper=aenean&sapien=lectus&a=pellentesque&libero=eget&nam=nunc&dui=donec",
  "photo": "http://dummyimage.com/600x600.png/ff4444/ffffff"
}, {
  "description": "congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor",
  "link": "https://trellian.com/turpis.jsp?lacinia=maecenas&nisi=tristique&venenatis=est&tristique=et&fusce=tempus&congue=semper&diam=est&id=quam&ornare=pharetra&imperdiet=magna&sapien=ac&urna=consequat&pretium=metus&nisl=sapien&ut=ut&volutpat=nunc&sapien=vestibulum&arcu=ante&sed=ipsum&augue=primis&aliquam=in&erat=faucibus&volutpat=orci&in=luctus&congue=et&etiam=ultrices&justo=posuere&etiam=cubilia&pretium=curae&iaculis=mauris&justo=viverra&in=diam&hac=vitae&habitasse=quam&platea=suspendisse&dictumst=potenti&etiam=nullam&faucibus=porttitor&cursus=lacus&urna=at&ut=turpis&tellus=donec&nulla=posuere&ut=metus&erat=vitae&id=ipsum&mauris=aliquam&vulputate=non&elementum=mauris&nullam=morbi&varius=non&nulla=lectus&facilisi=aliquam&cras=sit&non=amet&velit=diam&nec=in&nisi=magna&vulputate=bibendum&nonummy=imperdiet&maecenas=nullam&tincidunt=orci&lacus=pede&at=venenatis&velit=non&vivamus=sodales&vel=sed&nulla=tincidunt&eget=eu&eros=felis&elementum=fusce&pellentesque=posuere&quisque=felis&porta=sed&volutpat=lacus&erat=morbi&quisque=sem&erat=mauris&eros=laoreet&viverra=ut&eget=rhoncus&congue=aliquet&eget=pulvinar&semper=sed&rutrum=nisl&nulla=nunc&nunc=rhoncus",
  "photo": "http://dummyimage.com/600x600.png/dddddd/000000"
}, {
  "description": "duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor",
  "link": "http://cmu.edu/faucibus/cursus/urna/ut.html?sapien=quisque&dignissim=porta&vestibulum=volutpat&vestibulum=erat&ante=quisque&ipsum=erat&primis=eros&in=viverra&faucibus=eget&orci=congue&luctus=eget&et=semper&ultrices=rutrum&posuere=nulla&cubilia=nunc&curae=purus&nulla=phasellus&dapibus=in&dolor=felis&vel=donec&est=semper&donec=sapien&odio=a&justo=libero&sollicitudin=nam&ut=dui&suscipit=proin&a=leo&feugiat=odio&et=porttitor&eros=id&vestibulum=consequat&ac=in&est=consequat&lacinia=ut&nisi=nulla&venenatis=sed&tristique=accumsan&fusce=felis&congue=ut&diam=at&id=dolor&ornare=quis&imperdiet=odio&sapien=consequat&urna=varius&pretium=integer&nisl=ac&ut=leo&volutpat=pellentesque&sapien=ultrices&arcu=mattis&sed=odio&augue=donec&aliquam=vitae&erat=nisi&volutpat=nam&in=ultrices&congue=libero&etiam=non&justo=mattis&etiam=pulvinar&pretium=nulla&iaculis=pede&justo=ullamcorper&in=augue",
  "photo": "http://dummyimage.com/600x600.png/ff4444/ffffff"
}, {
  "description": "nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis",
  "link": "http://army.mil/pellentesque/ultrices/phasellus.html?mauris=ac&morbi=neque&non=duis&lectus=bibendum&aliquam=morbi&sit=non&amet=quam&diam=nec&in=dui&magna=luctus&bibendum=rutrum&imperdiet=nulla&nullam=tellus&orci=in&pede=sagittis&venenatis=dui&non=vel&sodales=nisl&sed=duis&tincidunt=ac&eu=nibh&felis=fusce&fusce=lacus&posuere=purus&felis=aliquet&sed=at&lacus=feugiat&morbi=non&sem=pretium&mauris=quis",
  "photo": "http://dummyimage.com/600x600.png/dddddd/000000"
}, {
  "description": "pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet",
  "link": "http://soundcloud.com/ac/enim/in/tempor.json?bibendum=habitasse&felis=platea&sed=dictumst&interdum=maecenas&venenatis=ut&turpis=massa&enim=quis&blandit=augue&mi=luctus&in=tincidunt&porttitor=nulla&pede=mollis&justo=molestie&eu=lorem&massa=quisque&donec=ut&dapibus=erat&duis=curabitur&at=gravida&velit=nisi&eu=at&est=nibh&congue=in&elementum=hac&in=habitasse&hac=platea&habitasse=dictumst&platea=aliquam&dictumst=augue&morbi=quam&vestibulum=sollicitudin&velit=vitae&id=consectetuer&pretium=eget&iaculis=rutrum&diam=at&erat=lorem&fermentum=integer&justo=tincidunt&nec=ante&condimentum=vel&neque=ipsum&sapien=praesent&placerat=blandit&ante=lacinia&nulla=erat&justo=vestibulum&aliquam=sed&quis=magna&turpis=at&eget=nunc&elit=commodo&sodales=placerat&scelerisque=praesent&mauris=blandit&sit=nam&amet=nulla&eros=integer&suspendisse=pede&accumsan=justo&tortor=lacinia&quis=eget&turpis=tincidunt&sed=eget&ante=tempus&vivamus=vel&tortor=pede",
  "photo": "http://dummyimage.com/600x600.png/dddddd/000000"
}, {
  "description": "dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus",
  "link": "http://creativecommons.org/vestibulum/velit/id/pretium/iaculis.png?sollicitudin=massa&ut=volutpat&suscipit=convallis&a=morbi&feugiat=odio&et=odio&eros=elementum&vestibulum=eu&ac=interdum&est=eu&lacinia=tincidunt&nisi=in&venenatis=leo&tristique=maecenas&fusce=pulvinar&congue=lobortis&diam=est&id=phasellus&ornare=sit&imperdiet=amet&sapien=erat&urna=nulla&pretium=tempus&nisl=vivamus&ut=in&volutpat=felis&sapien=eu&arcu=sapien",
  "photo": "http://dummyimage.com/600x600.png/ff4444/ffffff"
}, {
  "description": "volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque",
  "link": "https://examiner.com/blandit/lacinia.aspx?nonummy=condimentum",
  "photo": "http://dummyimage.com/600x600.png/ff4444/ffffff"
}, {
  "description": "sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et",
  "link": "https://fastcompany.com/quam/a/odio/in/hac.html?vulputate=posuere&vitae=cubilia&nisl=curae&aenean=donec&lectus=pharetra&pellentesque=magna&eget=vestibulum&nunc=aliquet&donec=ultrices&quis=erat&orci=tortor&eget=sollicitudin&orci=mi&vehicula=sit&condimentum=amet&curabitur=lobortis&in=sapien&libero=sapien&ut=non&massa=mi&volutpat=integer&convallis=ac&morbi=neque&odio=duis&odio=bibendum&elementum=morbi&eu=non&interdum=quam&eu=nec&tincidunt=dui&in=luctus&leo=rutrum&maecenas=nulla&pulvinar=tellus&lobortis=in&est=sagittis&phasellus=dui&sit=vel&amet=nisl&erat=duis&nulla=ac&tempus=nibh&vivamus=fusce&in=lacus&felis=purus",
  "photo": "http://dummyimage.com/600x600.png/ff4444/ffffff"
}, {
  "description": "elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum",
  "link": "https://hugedomains.com/quis/turpis/sed/ante/vivamus/tortor.aspx?aliquet=et&pulvinar=ultrices&sed=posuere&nisl=cubilia&nunc=curae&rhoncus=nulla&dui=dapibus&vel=dolor&sem=vel&sed=est&sagittis=donec&nam=odio&congue=justo&risus=sollicitudin&semper=ut&porta=suscipit&volutpat=a&quam=feugiat&pede=et&lobortis=eros&ligula=vestibulum&sit=ac&amet=est&eleifend=lacinia&pede=nisi&libero=venenatis&quis=tristique&orci=fusce&nullam=congue&molestie=diam&nibh=id&in=ornare&lectus=imperdiet&pellentesque=sapien&at=urna&nulla=pretium&suspendisse=nisl&potenti=ut&cras=volutpat&in=sapien&purus=arcu",
  "photo": "http://dummyimage.com/600x600.png/5fa2dd/ffffff"
}];

router.get('/',function(req,res){
  Event.create(newEvents, function(err){
        if (err){
          console.log(err);
          res.send('Error seeding database');
        } else {
          console.log('Seed completed');
          res.redirect('/');
        }
  });
});

module.exports = router;
